// resources/assets/js/components/InteractiveVideoNotes.vue
<style>
</style>

<template>
    <section id="video-notes">
        <header>
            <h3 class="hide">Notizen</h3>
        </header>

        <form id="notes-form" class="ui form">

            <div class="field">
                <label for="note-content" class="hide">Notizen</label>
                <textarea disabled="disabled"  id="note-content" placeholder="Wählen Sie ein »Fähnchen« und geben Sie Ihre Notizen ein." maxlength="500" ref="note-content" v-model="content" debounce="500"></textarea>
            </div>

        </form>
        <div id="notes-progress" class="ui disabled bottom attached green indicating progress" data-percent="100">
            <div class="bar"></div>
        </div>
    </section>

</template>

<script>
    module.exports = {
        props: ['content'],

        ready: function () {
            // jQuery laden
            var $ = require('jquery');
            window.$ = $;
            window.jQuery = $;
            // Semantic UI laden
            require('../../semantic/dist/semantic.js');

            $('#notes-progress').progress();
        },

        watch: {
            content: function () {
                    this.$dispatch('changedContent', this.content);
            }
        }
    }
</script>

// resources/assets/js/components/InteractiveVideoNotes.jsx
var InteractiveVideoNotes = React.createClass({

    componentDidMount: function ()
    {
        $('#notes-progress').progress();
    },

    render: function ()
    {

        return (
            <section id="video-notes">
                <header>
                    <h3 className="hide">Notizen</h3>
                </header>

                <form id="notes-form" className="ui form">

                    <div className="field">
                        <label htmlFor="note-content" className="hide">Notizen</label>
                        <textarea disabled="disabled"  id="note-content" placeholder="Wählen Sie ein »Fähnchen« und geben Sie Ihre Notizen ein." maxLength="500" ref="textarea" />
                    </div>

                </form>
                <div id="notes-progress" className="ui disabled bottom attached green indicating progress" data-percent="100">
                    <div className="bar"></div>
                </div>

            </section>
        );
    }
});

export default InteractiveVideoNotes;
